# Python, Numpy and Vectorization

## Outline
- [&nbsp;1.1 Goals](#toc_1.1)
- [&nbsp;1.2 Useful References](#toc_1.2)

In [2]:
import numpy as np 
import time

<a name="toc_1.1"></a>
## 1.1 Goals
- Review some features of NumPy and Python

<a name="toc_1.2"></a>
## 1.2 Useful References
- NumPy documnetation including a basic introduction: [NumPy.org](https://NumPy.org/doc/stable/)
- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)

### Vector Creation
Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.

In [9]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4); print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample((4,3)); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.72576893 0.15165962 0.4015075  0.79917627], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [[0.32583689 0.1113331  0.55711943]
 [0.04007517 0.98286282 0.3315593 ]
 [0.06731054 0.85148856 0.05377323]
 [0.8251883  0.00586286 0.49111087]], a shape = (4, 3), a data type = float64


In [12]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.22996279 0.53153758 0.0767035  0.73396753], a shape = (4,), a data type = float64


In [13]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [14]:
a = np.arange(10)
print(a)

try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


In [3]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

In [4]:
X

array([[1],
       [2],
       [3],
       [4]])

In [5]:
X.shape

(4, 1)

In [6]:
X[1]

array([2])